### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by laban211** [tobiastimm/subliminalr#1]
I'm a big fan of the theme and would love to use it when writing LaTeX documents.

**Comment by tobiastimm** [comment]
Okay. Haven't worked so much with LaTeX. Do you have any idea in mind for the usage of the colors?

**Comment by laban211** [comment]
I'll look into it, I'll get back to you!

**Comment by laban211** [comment]
Unfortunately, I don't have any prior experience with writing VS Code themes. I used the "Developer: Inspect TM Scopes" and came up with some suggestions though.

- keyword = red
- support.class = green
- variable.parameter = yellow
- support.function = blue
- entity.name = green
- constant.character = green
- constant.numeric = yellow
- markup.italic = green and italic text
- markup.bold = green and bold text

This should cover the basic syntax of at least the kind of documents I'm working with. Will this be enough for you to work with, or can I help some more?

**Comment by tobiastimm** [comment]
@laban211 an example file would be great! I will try to implement that on the weekend

**Comment by laban211** [comment]
http://physics.clarku.edu/sip/tutorials/TeX/intro.html

This should cover pretty much all of it.

**Comment by tobiastimm** [comment]
@laban211 I've looked a bit into this. Most of this should be fixed, if i convert the theme to my more general syntax, that I'm also using in `Raiju - Next` or `Sceanic`. I will try to convert SubliminalR tomorrow 😄

**Comment by tobiastimm** [comment]
@laban211 could you try out the new `SubliminalR - Next` theme combined with the LaTeX language extension? 😄

**Comment by laban211** [comment]
It seems to work!😃 The main color my files seems to be yellow (support.function). Is there any logic why this is the color of choice rather than something a bit softer like blue?

**Comment by tobiastimm** [comment]
this yellow is just the color for `support.function` taken from the original theme.
